Fix build issue on user build
The compilation flag "-Werror=unused-but-set-variable" cause the
following error:

hardware/intel/kernelflinger/libkernelflinger/blobstore.c:255:25:
error: variable '__sb' set but not used

Change-Id: I50b099fbed2510a4b369de647d024e1d4de20fb8
Signed-off-by: Leo Sartre <leox.sartre@intel.com>
Tracked-On: https://jira01.devtools.intel.com/browse/GMINL-7450